package Classes;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteWindow.java
 *
 * Created on 23/08/2011, 21:54:59
 */
import Cliente.TCPClient;
import Servidor.ServidorMultithreadTCP;
import com.google.gson.Gson;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjunior
 */
/**
 * 
 * @author André
 */
public class ClienteWindow extends javax.swing.JFrame {

    /** Creates new form ClienteWindow */
    public ClienteWindow() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jbConectar = new javax.swing.JButton();
        jbDesconectar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCampo1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jlQtdBombas = new javax.swing.JLabel();
        jbJogar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jtxtPlayer = new javax.swing.JTextField();
        jlMensagem = new javax.swing.JLabel();
        jtxtPtoContra = new javax.swing.JTextField();
        jtxtPtoPro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCampo2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Campo Minado");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, -1));

        jLabel1.setText("Campo inimigo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 240, -1));

        jLabel2.setText("Porta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 50, -1));

        jTextField2.setText("6789");
        jTextField2.setEnabled(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 170, -1));

        jbConectar.setText("Conectar");
        jbConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConectarActionPerformed(evt);
            }
        });
        jPanel1.add(jbConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, -1));

        jbDesconectar.setText("Desconectar");
        jbDesconectar.setEnabled(false);
        jbDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesconectarActionPerformed(evt);
            }
        });
        jPanel1.add(jbDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 140, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 500, 20));

        jtCampo1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtCampo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCampo1.setCellEditor(jtCampo1.getCellEditor());
        jtCampo1.setCellSelectionEnabled(true);
        jtCampo1.setRowHeight(30);
        jtCampo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCampo1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtCampo1);
        jtCampo1.getAccessibleContext().setAccessibleParent(jtCampo1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 240, 230));

        jLabel3.setText("Server:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 60, -1));

        jlQtdBombas.setText("0");
        jPanel1.add(jlQtdBombas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 40, -1));

        jbJogar.setText("Clique aqui para iniciar o jogo");
        jbJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJogarActionPerformed(evt);
            }
        });
        jPanel1.add(jbJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 270, -1));

        jLabel7.setText("Player:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 50, -1));
        jPanel1.add(jtxtPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 30, -1));

        jlMensagem.setFont(new java.awt.Font("Tahoma", 0, 18));
        jlMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMensagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jlMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 280, 50));

        jtxtPtoContra.setFont(new java.awt.Font("Tahoma", 0, 48));
        jtxtPtoContra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPtoContra.setText("0");
        jtxtPtoContra.setEnabled(false);
        jPanel1.add(jtxtPtoContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 80, 50));

        jtxtPtoPro.setFont(new java.awt.Font("Tahoma", 0, 48));
        jtxtPtoPro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPtoPro.setText("0");
        jtxtPtoPro.setEnabled(false);
        jPanel1.add(jtxtPtoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 80, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("x");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 40, 50));

        jLabel6.setText("Seu campo");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, -1));

        jLabel8.setText("Bombas:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 60, -1));

        jtCampo2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtCampo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "A", "B", "C", "D", "E", "F", "G"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCampo2.setCellSelectionEnabled(true);
        jtCampo2.setRowHeight(30);
        jtCampo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCampo2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtCampo2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 240, 230));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-568)/2, (screenSize.height-527)/2, 568, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void jbConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConectarActionPerformed
        try {
            String server = jTextField1.getText();
            int porta = Integer.parseInt(jTextField2.getText());
            tcpClient = new TCPClient(server, porta, this);
            confTela(0);// para jogar
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            confTela(1); //para conectar
        }
    }//GEN-LAST:event_jbConectarActionPerformed

    private void jbDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesconectarActionPerformed
        DefaultTableModel tableModel1 = (DefaultTableModel) jtCampo1.getModel();
        DefaultTableModel tableModel2 = (DefaultTableModel) jtCampo2.getModel();
        try {
            tcpClient.closeConnection();
            jTextField1.setText("");
            jlQtdBombas.setText("0");
            confTela(1); //para conectar
            bBlock = false;

            for (int i = 0; i < 7; i++) {
                for (int j = 0; j < 7; j++) {
                    tableModel1.setValueAt(null, i, j);
                    tableModel2.setValueAt(null, i, j);
                }
            }
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_jbDesconectarActionPerformed

    private void jtCampo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCampo1MouseClicked
        // TODO add your handling code here:
        int iColumn, iRow;

        DefaultTableModel tableModel1 = (DefaultTableModel) jtCampo1.getModel();

        if (bBlock == false) {

            Object oValue = new Object();

            iRow = jtCampo1.getSelectedRow();
            iColumn = jtCampo1.getSelectedColumn();

            evt.consume();

            try {

                if (iRow != -1) {
                    oValue = tableModel1.getValueAt(iRow, iColumn);
                    if (oValue == null) {
                        tableModel1.setValueAt("X", iRow, iColumn);
                        mCampo1.setValue(iRow, iColumn);
                        jlQtdBombas.setText(Integer.toString(Integer.parseInt(jlQtdBombas.getText()) + 1));

                    } else {
                        tableModel1.setValueAt(null, iRow, iColumn);

                        mCampo1.remValue(iRow, iColumn);
                        jlQtdBombas.setText(Integer.toString(Integer.parseInt(jlQtdBombas.getText()) - 1));
                    }
                }
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jtCampo1MouseClicked

    private void jtCampo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCampo2MouseClicked
        // TODO add your handling code here:
        int iColumn, iRow;
        Object oValue = new Object();

        DefaultTableModel tableModel2 = (DefaultTableModel) jtCampo2.getModel();
        jtCampo2.setSelectionBackground(Color.RED);

        iRow = jtCampo2.getSelectedRow();
        iColumn = jtCampo2.getSelectedColumn();

        int row = jtCampo2.getSelectedRow();

        oValue = tableModel2.getValueAt(iRow, iColumn);

        if (row != -1) {
            if (oValue == null) {
                tableModel2.setValueAt("X", iRow, iColumn);
                tcpClient.sendAttack("A" + Integer.toString(iRow) + Integer.toString(iColumn) + "N" + jtxtPlayer.getText()); //enviado para o servidor
            }
        }

    }//GEN-LAST:event_jtCampo2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened
    private void jbJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJogarActionPerformed
        // TODO add your handling code here:
        String jsonCampo;
        Gson gson = new Gson();

        if (mCampo1.validaQtdBombas(mCampo1.iMatrizCampo)) {
            jtCampo1.setEnabled(false);
            jtCampo1.setCellSelectionEnabled(false);
            jbJogar.setEnabled(false);
            jbJogar.setText("O jogo começou. Ataque seu inimigo!");
            bBlock = true;
            jsonCampo = gson.toJson(mCampo1.iMatrizCampo);

            try {
                tcpClient.sendCampo("N" + jtxtPlayer.getText() + "C" + jsonCampo); //enviado para o servidor
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        } else {
            jtCampo1.setEnabled(true);
            jtCampo1.setCellSelectionEnabled(true);
            jbJogar.setEnabled(true);
            jbJogar.setText("Clique aqui para iniciar o jogo!");
            bBlock = false;
            JOptionPane.showMessageDialog(this,
                    "Tem que por 10 bombas aí mano!", "Atenção!", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jbJogarActionPerformed

    public void escreverMensagem(String sMensagem) {
        iPontos++;
        jogador = sMensagem.substring(sMensagem.indexOf("N") + 1);

        if (sMensagem.substring(0, 1).equals("P")) {
            jlMensagem.setText("Poutz! Acertou.");
            jlMensagem.setForeground(Color.green);
            jtxtPtoPro.setText(Integer.toString(Integer.parseInt(jtxtPtoPro.getText()) + 1));
            if (jtxtPtoPro.getText().equals("10")) {
                JOptionPane.showMessageDialog(this,
                        "Você ganhou!", "Fim de Jogo!", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (sMensagem.substring(0, 1).equals("E")) {
            jlMensagem.setText("Há! Você errou!");
            jlMensagem.setForeground(Color.red);
        } else if (sMensagem.substring(0, 1).equals("X")) {
            jtxtPtoContra.setText(Integer.toString(Integer.parseInt(jtxtPtoContra.getText()) + 1));
            if (jtxtPtoContra.getText().equals("10")) {
                JOptionPane.showMessageDialog(this,
                        "Você perdeu!", "Fim de Jogo!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    public void confTela(int iConf) {

        if (iConf == 0) {//conf para jogar
            jTextField1.setEnabled(false);
            jtxtPlayer.setEnabled(false);
            jbConectar.setEnabled(false);
            jbDesconectar.setEnabled(true);
            jtCampo1.setEnabled(true);
            jtCampo1.setCellSelectionEnabled(true);
            jtCampo2.setEnabled(true);
            jbJogar.setEnabled(true);
        } else { //config para conectar
            jTextField1.setEnabled(true);
            jtxtPlayer.setEnabled(true);
            jbConectar.setEnabled(true);
            jbDesconectar.setEnabled(false);
            jtCampo1.setCellSelectionEnabled(false);
            jtCampo1.setEnabled(false);
            jtCampo2.setEnabled(false);
            jbJogar.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    
                public void run() {
                new ClienteWindow().setVisible(true);
            }
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new ClienteWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbConectar;
    private javax.swing.JButton jbDesconectar;
    private javax.swing.JButton jbJogar;
    private javax.swing.JLabel jlMensagem;
    private javax.swing.JLabel jlQtdBombas;
    private javax.swing.JTable jtCampo1;
    private javax.swing.JTable jtCampo2;
    private javax.swing.JTextField jtxtPlayer;
    private javax.swing.JTextField jtxtPtoContra;
    private javax.swing.JTextField jtxtPtoPro;
    // End of variables declaration//GEN-END:variables
    private TCPClient tcpClient;
    private ServidorMultithreadTCP tcpServer;
    MatrizCampo mCampo1 = new MatrizCampo();
    MatrizCampo mCampo2 = new MatrizCampo();
    boolean bBlock;
    public int iPontos;
    String jogador = new String();
}
