/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Informações.java
 *
 * Created on 09/11/2011, 18:10:52
 */
package GUI;

/**
 *
 * @author Andre
 */
public class Informacoes extends javax.swing.JFrame {

    /** Creates new form Informações */
    public Informacoes() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 13));
        jTextArea1.setRows(5);
        jTextArea1.setText("Equipe:\n\nAndré S. Ananias Garcia - RA: 335090972\nRafael Garcia - RA: 330080983\nCarlos Zambianco - RA: 330080959\nRafael Tinelli - RA: 330080977");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 120));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Instruções\n\n- Ao executar o projeto clique no menu \"Servidor\" para conectar o \n  servidor. (Nada aparecerá, o servidor simplesmente será conectado).\n- Clique no menu \"Cliente\". Aparecerá a janela de um jogador.\n- Informe o IP do servidor.\n- É necessário informar no campo \"Player\" o número 0 (zero) para \n  um dos jogadores e 1 para o outro.\n- Clique em \"Conectar\".\n- Monte seu campo (no lado direito) enquanto o outro jogador monta\n  o dele. É necessário selecionar 10 campos.\n- Após montar o campo, clique em \"iniciar o jogo\".\n- Clique no campo inimigo (no lado esquerdo) para atacar seu \n  oponente.\n- O primeiro que fazer 10 pontos vence.\n- Bom jogo!");
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 410, 250));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Considerações\n\n- O servidor guarda os campos em um arquivo \".txt\" na pasta do \n  projeto, sendo \"M0.txt\" para o campo do jogador 0 e \"M1.txt\" \n  para o jogador 1.");
        jTextArea3.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 410, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
                public void run() {
                new Informacoes().setVisible(true);
            }
    
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new Informacoes().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
